# Generated by Django 3.2.7 on 2021-09-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixelcounter',
            name='hex_code',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='pixelcounter',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
